d2bs/kolbot/libs/bots/SealLeader.js, d2bs/kolbot/libs/bots/SealLeecher.js
Leechers will now end script after Diablo is killed.
=> Fixed SealLeecher/Leader

d2bs/kolbot/libs/common/Pather.js
Fix for issue #274 :
- 101 -> 100 & 129 -> 128, initial area check wasn't implemented.
- 83 -> 120 also checked ancients quest, adjusted to check council quest instead.
=> Issue #274 fix

d2bs/kolbot/libs/OOG.js
Let me know if you want anything added in the starters in relation to this @noah-
=> Added getProfile/setProfile D2Bot# wrapper functions

d2bs/kolbot/tools/ToolsThread.js
1) Press Numpad 0 to precast;
2) Added additional stats to numpad+ output;
=> Some fixes in ToolsThread

d2bs/kolbot/libs/bots/Rushee.js
Move A2 staff directly to inventory for issue #425 .
=> Rushee.js cubeStaff() fix

d2bs/kolbot/D2BotLead.dbj, d2bs/kolbot/libs/bots/ChestMania.js, d2bs/kolbot/libs/common/Attacks/Assassin.js, d2bs/kolbot/libs/common/Config.js, d2bs/kolbot/libs/common/Cubing.js, d2bs/kolbot/libs/common/Town.js, d2bs/kolbot/libs/config/Assassin.js
New Config.AggressiveCloak option for Assassins
New random game name/password option
Various formatting fixes
=> Added doPrecast to Chestmania; Added two new features

d2bs/kolbot/libs/common/Misc.js
completed the list with range of skills
=> Missing range definitions in misc.js

d2bs/kolbot/libs/common/Misc.js, d2bs/kolbot/libs/config/Amazon.js, d2bs/kolbot/libs/config/Assassin.js, d2bs/kolbot/libs/config/Barbarian.js, d2bs/kolbot/libs/config/Druid.js, d2bs/kolbot/libs/config/Necromancer.js, d2bs/kolbot/libs/config/Paladin.js, d2bs/kolbot/libs/config/Sorceress.js
range of druid skill Artic Blast based on level
=> Arctic blast

d2bs/kolbot/libs/common/Precast.js
creating pull request for utf8
=> precast fix for druid sage

d2bs/kolbot/libs/common/Misc.js
- new PacketBuilder() interface for simplifying packet building (see examples in code)
- Misc.getUIFlags() to assist checking and debugging npc interactions and game states
=> QoL additions for scripting

d2bs/kolbot/libs/config/Amazon.js, d2bs/kolbot/libs/config/Assassin.js, d2bs/kolbot/libs/config/Barbarian.js, d2bs/kolbot/libs/config/Druid.js, d2bs/kolbot/libs/config/Necromancer.js, d2bs/kolbot/libs/config/Paladin.js, d2bs/kolbot/libs/config/Sorceress.js, d2bs/kolbot/tools/Party.js
party.js - Fixed to include Town.js. It wasn't initializing config properly because NPC variables were not defined.
character configs - removed non-standard characters from past commits that were messing up with file encoding
=> Fix party thread

d2bs/kolbot/libs/config/Builds/Class.Build.js, d2bs/kolbot/libs/config/Builds/Sorceress.ExampleBuild.js, d2bs/kolbot/tools/AutoBuildThread.js, d2bs/kolbot/tools/MapThread.js
-include town.js for autobuild
-minor format fix
=> add missing include for autobuild

d2bs/kolbot/D2BotMule.dbj, d2bs/kolbot/libs/bots/Follower.js, d2bs/kolbot/libs/common/Attack.js, d2bs/kolbot/libs/common/CollMap.js, d2bs/kolbot/libs/common/Misc.js, d2bs/kolbot/libs/common/Pather.js, d2bs/kolbot/libs/common/Town.js
D2BotMule - add delay before town check to give enough time for initialization
Misc - re-enable flash to better handle desync issues
CollMap - add function for random coordinate validation
=> d2botmule and pather fixes

d2bs/kolbot/D2BotChannel.dbj, d2bs/kolbot/D2BotFollow.dbj, d2bs/kolbot/D2BotLead.dbj, d2bs/kolbot/D2BotPubJoin.dbj, d2bs/kolbot/libs/OOG.js
OOG - Updated findCharacter, getCharacters, and loginCharacter functions to handle up to 24 characters.
=> Add support for accounts with more than 8 chars

d2bs/kolbot/D2BotChannel.dbj, d2bs/kolbot/D2BotFollow.dbj, d2bs/kolbot/D2BotLead.dbj, d2bs/kolbot/D2BotPubJoin.dbj, d2bs/kolbot/libs/AutoMule.js, d2bs/kolbot/libs/GameAction.js, d2bs/kolbot/libs/MuleLogger.js, d2bs/kolbot/libs/OOG.js, d2bs/kolbot/libs/bots/Crafting.js, d2bs/kolbot/libs/common/Misc.js, d2bs/kolbot/libs/common/Pather.js, d2bs/kolbot/libs/common/Pickit.js, d2bs/kolbot/libs/common/Prototypes.js, d2bs/kolbot/libs/common/Town.js
add support for account with more than 8 chars
add flash for various move/town tasks to alleviate desync issues
fix item color handling for non-standard string tables
fix bug with runeword base check
=> >8 char support and various fixes

d2bs/kolbot/libs/GameAction.js, d2bs/kolbot/libs/MuleLogger.js, d2bs/kolbot/libs/common/Misc.js
GameAction, MuleLogger, Misc
-Add missing var declaration from last commit
=> Add missing var declaration

d2bs/kolbot/libs/GameAction.js, d2bs/kolbot/libs/MuleLogger.js, d2bs/kolbot/libs/common/Misc.js
GameAction, MuleLogger, Misc
-Add missing var declaration from last commit
=> Add missing var declaration(u)

d2bs/kolbot/libs/common/Storage.js
Fix Storage.IsLocked error by checking for both parent type and gid
=> Fix Storage.IsLocked error

d2bs/kolbot/D2BotMule.dbj, d2bs/kolbot/libs/AutoMule.js
add support for more than 8 characters for mule account
=> more char support for automule

d2bs/kolbot/libs/common/Misc.js, d2bs/kolbot/libs/common/Pather.js, d2bs/kolbot/libs/common/Pickit.js
Misc.js, Pather.js, Pickit.js
-Fix occasional item pick fail caused after town visit because useTeleport variable wasn't re-evaluated
=> Fix item pick fail

d2bs/kolbot/libs/GameAction.js, d2bs/kolbot/libs/MuleLogger.js, d2bs/kolbot/libs/bots/Travincal.js, d2bs/kolbot/libs/common/Misc.js, d2bs/kolbot/libs/common/Pather.js, d2bs/kolbot/libs/common/Prototypes.js
GameAction.js, MuleLogger.js, Misc.js, Prototypes.js
-Add unit code check for possible base stat name duplicates
Pather.js, Travincal.js
-Fix moveToExit to work properly for array of target areas
-Fix gate opening in A5 which continued to re-click when it was already in opening animation
=> Add code check for items and fix moveToExit

d2bs/kolbot/default.dbj, d2bs/kolbot/libs/common/Attacks/Amazon.js, d2bs/kolbot/libs/common/Attacks/Barbarian.js, d2bs/kolbot/libs/common/Misc.js, d2bs/kolbot/libs/common/Town.js, d2bs/kolbot/tools/AntiHostile.js
AntiHostile.js
-Keep thread running for subsequent hostiles and quit if bot fails to go to town
class attacks, Town.js
-Add repair check for barb/amazons before attack
Misc.js
-Add year/date timestamp for item and error logs
Default.dbj
-Add check for gameaction tag length
=> Fix antihostile.js and other changes

d2bs/kolbot/libs/bots/Summoner.js, d2bs/kolbot/libs/common/Pather.js
Concerns the changes requested here https://github.com/kolton/d2bot-with-kolbot/commit/2ddba43c4d31de92fdebb1a798e7540e8ff7040a#comments
Would be nice if someone who experienced the bug could test this.
=> Fix Warriv use

d2bs/kolbot/libs/common/Config.js, d2bs/kolbot/libs/config/Amazon.js, d2bs/kolbot/libs/config/Assassin.js, d2bs/kolbot/libs/config/Barbarian.js, d2bs/kolbot/libs/config/Druid.js, d2bs/kolbot/libs/config/Necromancer.js, d2bs/kolbot/libs/config/Paladin.js, d2bs/kolbot/libs/config/Sorceress.js, d2bs/kolbot/tools/ToolsThread.js
Improvement for Quit List, added Quit List Delay to prevent Realm Down.
=> Add QuitListDelay option

d2bs/kolbot/D2BotGameAction.dbj
- Don't create games on join error
- Attempt to retrieve from unhandled UI locations
- Option to release key after stop
=> D2BotGameAction.dbj fix to not create games on error
